language: php
sudo: false
script: php test.php
deploy:
  provider: releases
  api_key:
    secure: nlz0KviP1/G2I5tY6Po1h9jAIAlu0ZBtGaGVh8KXAfLY1l2Dxz6BdtIf4mW6khhUuboTXa0Gc1ssE5sEStwdGYArgR9CS22XP2acig5jSEoCtibbhv7kbsoCHNQVJAL7QVTPPH/XPGsVW1REkJ9cuJ0LlpcPsVLp9vrCZZGT70NuO42Zq9Ebg4jygrAKCMaOYA6JalEsdXFOM8TviM6miEZm4IJyBRPBUEVynpFsN6LLWQdomZL/wgvbsXmZ3em35s+sSKqO2UvvzVRrVDKF+i432ZlrXvdku5M9NgZA2uoNmR70qrz3UnpaaSD90YZWUPttlPeIOakBl41u/EMgbnguHd/hZpyuWmkjFKOkkdFTFzTXvM2vklpo76B0muwhly9FP/B1OUj4gcz6Y/ARtwbetS1adzaCYtDTO8sh1aPxbh9LZjfb3hbP6jctRtYbUl1rP8CRtADWx2ELH/y4Z8eU4Mb/RmFKGjY6jYw3CnOYLTDK5JBGvQo0rWoireeZsI0uEiUrTAJRE0qN1rsc6jQhNk92WknJVgaxmXbxGBabwM4XltFMuVV7wXHQXm+pSrTGDZHtn++5rCFmV5KK6fSW24sfDKk9IVjLkD+oNnK6KXIa7N1Y2t4mOmmy4bKcfqYfN45u/Wl7vs5K54A0hgbJbcIIhTg/sUy0YBlzER0=
  file: test.php
  on:
    repo: Nitin-Er/TravisTest