language: php
sudo: false
script: php test.php
deploy:
  provider: releases
  api_key:
    secure: RCcERo/SsBF36M5qctc9ffFpHODPJ6ambTlhpjSLOgvYYtnDbxyCkpBXRI0bRo7j/UOvwISMFzIXjRcu+nZPYuznlY5Y098eIZ6hzW6qHIhPvwd0+zcpgWzkio7IeYd8JSsgY31hJDDgrg0xSGyV3PJeMGFSDvpSmlXFzASf9F6XBTZtTJOJxVYMpvUUU9eUz0FPileQOBoU/1WlU4fMTJyioG3S0tFqFuu2zH+ZoVKNBbhvxQdEVHc3v1SZ5kGHok/Qo97mHLnz6JeHrT4yj8FcO3J0ZgWL9TOdghauNXhuqeRvVF6NQDiwTAS60tm7vvnuFPj4mXtnzaH59Xz9CEILHjwCnaJwL0BmOpXHp2UrOUCPbs4tZ3bj+ClbJ2+HflpwQK9DlrIab/W1PNhGuDwqnZkN9vK2/2DfhymjJX5o+aEhx8ht9rM6rgK82swWzUYQM5iKOQqtSm23/+ORKahYmjqAOgohnVpg4FzUzKjp0HTo9I/6GE2fMCz7xBolnwHnJ3i4XZpSCHrHWywVo9XHBVF3sFqR3ScJ2GMZtM2DwtMDrKYQ8bKggU5W1CLj21WZZpfhyWhCeJ7yOjMApJB84eYhgi783Eo68rlz7Ex3Ww6+GsQjQ8nYD8SqFZ3eNoKYCiQTOMuXea9IGYynyJlv5EZXMTAfQwnip0JA2qE=
  file: Files/test.txt
  skip_cleanup: true
  on:
    repo: Nitin-Er/TravisTest